/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javacosmetic;

import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ozlem
 */
public class GirisGuı extends javax.swing.JFrame {
    ImageIcon background= new ImageIcon(getClass().getResource("login.gif"));
    ArrayList<Member> arrMember=new ArrayList();
    
    
    public GirisGuı() {
        initComponents();
        this.setLocationRelativeTo(null);// guiyi ekrana ortalama kodu
        MemberClass.setMemberArr(arrMember);
        panelOpen.setVisible(true);
        panelRegister.setVisible(false);
        panelLogin.setVisible(false);
        lblinlogin.setVisible(false);
        lblinregister.setVisible(false);
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        panelOpen = new javax.swing.JPanel();
        buttonLogin = new javax.swing.JButton();
        buttonRegister = new javax.swing.JButton();
        panelLogin = new javax.swing.JPanel();
        Nick = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        tfNick = new javax.swing.JTextField();
        btLogininLogin = new javax.swing.JButton();
        btregisterinLogin = new javax.swing.JButton();
        lblinlogin = new javax.swing.JLabel();
        btbacktomenuinlogin = new javax.swing.JButton();
        btShowPassword = new javax.swing.JCheckBox();
        panelRegister = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfnickinregister = new javax.swing.JTextField();
        tfpasswordinregister = new javax.swing.JTextField();
        tfpasswordagain = new javax.swing.JTextField();
        btregisterinregister = new javax.swing.JButton();
        lblinregister = new javax.swing.JLabel();
        btbacktomenuinregister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(2, 0, 42));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(150, 350, 150, 350, new javax.swing.ImageIcon(getClass().getResource("/javacosmetic/login.gif")))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 850));

        jLayeredPane2.setLayout(new java.awt.CardLayout());

        panelOpen.setBackground(new java.awt.Color(2, 0, 42));

        buttonLogin.setBackground(new java.awt.Color(255, 204, 204));
        buttonLogin.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(102, 0, 102));
        buttonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javacosmetic/bck.png"))); // NOI18N
        buttonLogin.setText("Login");
        buttonLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        buttonRegister.setBackground(new java.awt.Color(255, 204, 204));
        buttonRegister.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        buttonRegister.setForeground(new java.awt.Color(102, 0, 102));
        buttonRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javacosmetic/bck.png"))); // NOI18N
        buttonRegister.setText("Register");
        buttonRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpenLayout = new javax.swing.GroupLayout(panelOpen);
        panelOpen.setLayout(panelOpenLayout);
        panelOpenLayout.setHorizontalGroup(
            panelOpenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpenLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(panelOpenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130))
        );
        panelOpenLayout.setVerticalGroup(
            panelOpenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpenLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(buttonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jLayeredPane2.add(panelOpen, "card2");

        panelLogin.setBackground(new java.awt.Color(2, 0, 42));

        Nick.setBackground(new java.awt.Color(255, 204, 204));
        Nick.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        Nick.setForeground(new java.awt.Color(255, 153, 153));
        Nick.setText("Nick:");

        password.setBackground(new java.awt.Color(255, 204, 204));
        password.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 153, 153));
        password.setText("Password:");

        btLogininLogin.setBackground(new java.awt.Color(255, 153, 153));
        btLogininLogin.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        btLogininLogin.setForeground(new java.awt.Color(102, 0, 102));
        btLogininLogin.setText("Login");
        btLogininLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogininLoginActionPerformed(evt);
            }
        });

        btregisterinLogin.setBackground(new java.awt.Color(255, 153, 153));
        btregisterinLogin.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        btregisterinLogin.setForeground(new java.awt.Color(102, 0, 102));
        btregisterinLogin.setText("Haven't an account? Register!");
        btregisterinLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btregisterinLoginActionPerformed(evt);
            }
        });

        lblinlogin.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        lblinlogin.setForeground(new java.awt.Color(0, 153, 153));
        lblinlogin.setText("jLabel1");

        btbacktomenuinlogin.setBackground(new java.awt.Color(255, 153, 153));
        btbacktomenuinlogin.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        btbacktomenuinlogin.setForeground(new java.awt.Color(102, 0, 102));
        btbacktomenuinlogin.setText("Back to menu!");
        btbacktomenuinlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbacktomenuinloginActionPerformed(evt);
            }
        });

        btShowPassword.setBackground(new java.awt.Color(2, 0, 42));
        btShowPassword.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        btShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        btShowPassword.setText("Show Password");
        btShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShowPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btbacktomenuinlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btregisterinLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                        .addComponent(btLogininLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblinlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(password))
                        .addGap(41, 41, 41)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btShowPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfPassword)
                                .addComponent(tfNick, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nick)
                    .addComponent(tfNick, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(btShowPassword)
                .addGap(18, 18, 18)
                .addComponent(lblinlogin)
                .addGap(10, 10, 10)
                .addComponent(btLogininLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btregisterinLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btbacktomenuinlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLayeredPane2.add(panelLogin, "card3");

        panelRegister.setBackground(new java.awt.Color(2, 0, 42));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("Nick:");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 153));
        jLabel2.setText("Password:");

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("Password again:");

        btregisterinregister.setBackground(new java.awt.Color(255, 153, 153));
        btregisterinregister.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        btregisterinregister.setForeground(new java.awt.Color(102, 0, 102));
        btregisterinregister.setText("Register!");
        btregisterinregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btregisterinregisterActionPerformed(evt);
            }
        });

        lblinregister.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        lblinregister.setForeground(new java.awt.Color(0, 153, 153));
        lblinregister.setText("jLabel4");

        btbacktomenuinregister.setBackground(new java.awt.Color(255, 153, 153));
        btbacktomenuinregister.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        btbacktomenuinregister.setForeground(new java.awt.Color(102, 0, 102));
        btbacktomenuinregister.setText("Back to menu!");
        btbacktomenuinregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbacktomenuinregisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegisterLayout = new javax.swing.GroupLayout(panelRegister);
        panelRegister.setLayout(panelRegisterLayout);
        panelRegisterLayout.setHorizontalGroup(
            panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btregisterinregister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelRegisterLayout.createSequentialGroup()
                        .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfnickinregister, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfpasswordagain, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfpasswordinregister, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btbacktomenuinregister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblinregister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        panelRegisterLayout.setVerticalGroup(
            panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfnickinregister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfpasswordinregister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfpasswordagain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblinregister)
                .addGap(26, 26, 26)
                .addComponent(btregisterinregister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btbacktomenuinregister)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLayeredPane2.add(panelRegister, "card4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1401, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        panelLogin.setVisible(true);
        panelRegister.setVisible(false);
        panelOpen.setVisible(false);
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        
        panelRegister.setVisible(true);
        panelLogin.setVisible(false);
        panelOpen.setVisible(false);
    }//GEN-LAST:event_buttonRegisterActionPerformed

    private void btregisterinLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btregisterinLoginActionPerformed
        tfNick.setText("");
        tfPassword.setText("");
        panelRegister.setVisible(true);
        panelLogin.setVisible(false);
        panelOpen.setVisible(false);
        
    }//GEN-LAST:event_btregisterinLoginActionPerformed

    private void btLogininLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogininLoginActionPerformed
        
        
        String message = null;
        
        
        if(MemberClass.checkMember(tfNick.getText(), tfPassword.getText())){
           lblinlogin.setVisible(true);
           lblinlogin.setText("Log in is successful1");
           message="Welcome "+tfNick.getText()+", you are being redirected...";
            JOptionPane.showMessageDialog(this, message);
            try {
                Thread.sleep(1500);
            } catch (InterruptedException ex) {
                Logger.getLogger(GirisGuı.class.getName()).log(Level.SEVERE, null, ex);
            }
           GUI gui= new GUI(tfNick.getText());
           gui.setVisible(true);
           this.setVisible(false);
        }
        else{
            lblinlogin.setVisible(true);
            lblinlogin.setText("The nick or the password is wrong!!Try again.");
        }
        
            
            
        
        
    }//GEN-LAST:event_btLogininLoginActionPerformed

    private void btregisterinregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btregisterinregisterActionPerformed
        
        if(tfnickinregister.getText().equals("") || tfpasswordinregister.getText().equals("")|| tfpasswordagain.getText().equals("")){
            lblinregister.setText("You did not fill in the required fields!!");
        }
        else{
        if(MemberClass.isThereThisNick(tfnickinregister.getText())!=true){
        if(tfpasswordinregister.getText().equals(tfpasswordagain.getText())){
            lblinregister.setVisible(true);
            Member member=new Member(tfnickinregister.getText(),tfpasswordinregister.getText());
            
            arrMember.add(member);
            tfnickinregister.setText("");
            tfpasswordinregister.setText("");
            tfpasswordagain.setText("");
            lblinregister.setText("Register is successfu1!");
            
        }
        else {
            lblinregister.setVisible(true);
            lblinregister.setText("Passwords are different!Try again.");
        }
        }
        else{
        lblinregister.setText("The nick is already use.");
        }
    }
    }//GEN-LAST:event_btregisterinregisterActionPerformed

    private void btbacktomenuinregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbacktomenuinregisterActionPerformed
        panelOpen.setVisible(true);
        panelRegister.setVisible(false);
        panelLogin.setVisible(false);
    }//GEN-LAST:event_btbacktomenuinregisterActionPerformed

    private void btbacktomenuinloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbacktomenuinloginActionPerformed
        panelOpen.setVisible(true);
        panelRegister.setVisible(false);
        panelLogin.setVisible(false);
    }//GEN-LAST:event_btbacktomenuinloginActionPerformed

    private void btShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowPasswordActionPerformed
        if (btShowPassword.isSelected()) {
            tfPassword.setEchoChar((char) 0);
            }     
        else {
            tfPassword.setEchoChar('*');
             };
    }//GEN-LAST:event_btShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisGuı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisGuı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisGuı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisGuı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisGuı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nick;
    private javax.swing.JButton btLogininLogin;
    private javax.swing.JCheckBox btShowPassword;
    private javax.swing.JButton btbacktomenuinlogin;
    private javax.swing.JButton btbacktomenuinregister;
    private javax.swing.JButton btregisterinLogin;
    private javax.swing.JButton btregisterinregister;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblinlogin;
    private javax.swing.JLabel lblinregister;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelOpen;
    private javax.swing.JPanel panelRegister;
    private javax.swing.JLabel password;
    public javax.swing.JTextField tfNick;
    public javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfnickinregister;
    private javax.swing.JTextField tfpasswordagain;
    private javax.swing.JTextField tfpasswordinregister;
    // End of variables declaration//GEN-END:variables
}
